spring:
  application:
    name: ai-service
  mongodb:
    # uri: mongodb://mongo:mongo@localhost:27017/recom?authSource=admin
    uri: mongodb://mongo:mongo@mongo:27017/recom?authSource=admin
  kafka:
    # bootstrap-servers: localhost:9092
    bootstrap-servers: kafka:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: activity-processor-group
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fitness.aiservice.model.Activity
        spring.json.trusted.packages: "*"

kafka:
  topic:
    name: activity-events

# It will take the Gemini URL and Gemini KEY from Environment Variables - via Edit Configurations
gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_KEY}

eureka:
  client:
    serviceUrl:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka-service:8761/eureka/

server:
  port: 8083